apiVersion: v1
kind: Pod
metadata:
  name: dp-po
spec:
  containers:
  - name: nginx
    image: mysql:5.7
    ports: 
     - containerPort: 8080

    envFrom:
      - secretRef:
          name : db-secret

    