apiVersion: v1
kind: Pod
metadata:
  name: yellow
spec:
  containers:
    - name: lemon
      image: busybox
      command: ['sh', '-c', 'sleep 20']
      
      
    - name: gold
      image: redis
     