apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  initContainers:
    - name: sleep-init
      image: busybox
      command: ['sh', '-c', 'sleep 20']
  containers:
    - name: redis
      image: redis