apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: myapp
spec:
  containers:
  - name: wepapp
    image: nginx
    ports:
      - containerPort: 80

  volumes:
   - name: claim-log-1
     persistentVolumeClaim:
       claimName : claim-log-1

